[colors.primary]
# The primary colors for the terminal window
background = '#1b1f20'
foreground = '#d4d4d4'

[colors.cursor]
text = 'CellBackground'
cursor = 'CellForeground'

[colors.selection]
text = '#1b1f20'
background = '#fb916f'

[colors.normal]
# Normal colors used by applications
black = '#1b1f20'
red = '#d8866a'
green = '#2d8f6d'
yellow = '#e5c185'
blue = '#408da1'
magenta = '#bc3fbc'
cyan = '#4daaaa'
white = '#d4d4d4'

[colors.bright]
# Bright colors used for emphasis
black = '#60716d'
red = '#fb916f'
green = '#92ba92'
yellow = '#e2c08d'
blue = '#5590a4'
magenta = '#d670d6'
cyan = '#29b8db'
white = '#ffffff'