-- Generated by scripts/hypr2lua.
-- Source: /home/davilapai/.config/omarchy/themes/Tea4Omarchy/hyprland.conf

hl.config({
  general = {
    col = {
      active_border = "rgb(2d8f6d)",
      inactive_border = "rgb(1b1f20)",
    },
    border_size = 3,
    gaps_in = 5,
    gaps_out = 5,
  },
  group = {
    col = {
      border_active = "rgba(45,143,109,0.9)",
      border_inactive = "rgb(1b1f20)",
    },
    groupbar = {
      col = {
        active = "rgba(45,143,109,0.6)",
        inactive = "rgba(96,113,109,0.4)",
      },
      text_color = "rgb(2d8f6d)",
      text_color_inactive = "rgba(212,212,212,0.8)",
    },
  },
  decoration = {
    rounding = 4,
    rounding_power = 3,
    shadow = {
      enabled = true,
      render_power = 8,
      range = 8,
      color = "rgba(0,0,0,0.5)",
    },
  },
})
